name: 'Create or Update Comment'
description: 'Create or update an issue or pull request comment'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'lib/index.mjs'
