name: 'Issue to Quote'
description: 'Push quotes from issues to DynamoDB'
inputs:
  GITHUB_TOKEN:
    description: 'GitHub token'
    required: true
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'lib/index.mjs'
