name: 'Create or Update Comment'
description: 'Create or update an issue or pull request comment'
inputs:
  token:
    description: 'GITHUB_TOKEN or a repo scoped PAT.'
    default: ${{ github.token }}
runs:
  using: 'node16'
  main: 'lib/index.mjs'
