name: "Add quote to DB"
on:
  issues:
    types: [opened, edited]

jobs:
  insert:
    runs-on: ubuntu-latest
    steps:
    - uses: ./
      with:
        node-version: 18
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
