name: "Add quote to DB"
on:
  issues:
    types: [opened, edited]

jobs:
  insert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: ./
      env: 
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TableName: 'quotes-db-table'
      with:
        GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
